
---
- name: Configure Apache2 Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: Update APT
      apt:
        update_cache: yes

    - name: Install Python-apt
      apt:
        name: python-apt
        state: latest

    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Copy Apache2 configuration file
      copy:
        src: files/config/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy website file
      copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: Create symbolic link for enabling site
      file:
        src: /etc/apache2/mods-available/headers.load
        dest: /etc/apache2/mods-available/headers.load
        state: link
        force: yes
    
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
